// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/bldr/simple/protobuf_lite_ts.proto (package protobuf_lite_ts, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from "@aptre/protobuf-es-lite";
import { createMessageType, ScalarType } from "@aptre/protobuf-es-lite";

export const protobufPackage = "protobuf_lite_ts";

/**
 * @generated from message protobuf_lite_ts.ExampleMsg
 */
export interface ExampleMsg {
  /**
   * @generated from field: bytes example_field = 1;
   */
  exampleField?: Uint8Array;
  /**
   * @generated from field: string example_text = 2;
   */
  exampleText?: string;

};

// ExampleMsg contains the message type declaration for ExampleMsg.
export const ExampleMsg: MessageType<ExampleMsg> = createMessageType({
    typeName: "protobuf_lite_ts.ExampleMsg",
    fields: [
        { no: 1, name: "example_field", kind: "scalar", T: ScalarType.BYTES },
        { no: 2, name: "example_text", kind: "scalar", T: ScalarType.STRING },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
});

