// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.9.1
// source: github.com/aperturerobotics/bldr/simple/protobuf_lite_ts.proto

package main

import (
	base64 "encoding/base64"
	fmt "fmt"
	io "io"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

type ExampleMsg struct {
	unknownFields []byte
	ExampleField  []byte `protobuf:"bytes,1,opt,name=example_field,json=exampleField,proto3" json:"exampleField,omitempty"`
	ExampleText   string `protobuf:"bytes,2,opt,name=example_text,json=exampleText,proto3" json:"exampleText,omitempty"`
}

func (x *ExampleMsg) Reset() {
	*x = ExampleMsg{}
}

func (*ExampleMsg) ProtoMessage() {}

func (x *ExampleMsg) GetExampleField() []byte {
	if x != nil {
		return x.ExampleField
	}
	return nil
}

func (x *ExampleMsg) GetExampleText() string {
	if x != nil {
		return x.ExampleText
	}
	return ""
}

func (m *ExampleMsg) CloneVT() *ExampleMsg {
	if m == nil {
		return (*ExampleMsg)(nil)
	}
	r := new(ExampleMsg)
	r.ExampleText = m.ExampleText
	if rhs := m.ExampleField; rhs != nil {
		tmpBytes := make([]byte, len(rhs))
		copy(tmpBytes, rhs)
		r.ExampleField = tmpBytes
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ExampleMsg) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *ExampleMsg) EqualVT(that *ExampleMsg) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if string(this.ExampleField) != string(that.ExampleField) {
		return false
	}
	if this.ExampleText != that.ExampleText {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ExampleMsg) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ExampleMsg)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ExampleMsg message to JSON.
func (x *ExampleMsg) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.ExampleField) > 0 || s.HasField("exampleField") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("exampleField")
		s.WriteBytes(x.ExampleField)
	}
	if x.ExampleText != "" || s.HasField("exampleText") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("exampleText")
		s.WriteString(x.ExampleText)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ExampleMsg to JSON.
func (x *ExampleMsg) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ExampleMsg message from JSON.
func (x *ExampleMsg) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "example_field", "exampleField":
			s.AddField("example_field")
			x.ExampleField = s.ReadBytes()
		case "example_text", "exampleText":
			s.AddField("example_text")
			x.ExampleText = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the ExampleMsg from JSON.
func (x *ExampleMsg) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *ExampleMsg) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExampleMsg) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ExampleMsg) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.ExampleText) > 0 {
		i -= len(m.ExampleText)
		copy(dAtA[i:], m.ExampleText)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.ExampleText)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ExampleField) > 0 {
		i -= len(m.ExampleField)
		copy(dAtA[i:], m.ExampleField)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.ExampleField)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExampleMsg) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ExampleField)
	if l > 0 {
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	l = len(m.ExampleText)
	if l > 0 {
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (x *ExampleMsg) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("ExampleMsg {")
	if x.ExampleField != nil {
		if sb.Len() > 12 {
			sb.WriteString(" ")
		}
		sb.WriteString("example_field: ")
		sb.WriteString("\"")
		sb.WriteString(base64.StdEncoding.EncodeToString(x.ExampleField))
		sb.WriteString("\"")
	}
	if x.ExampleText != "" {
		if sb.Len() > 12 {
			sb.WriteString(" ")
		}
		sb.WriteString("example_text: ")
		sb.WriteString(strconv.Quote(x.ExampleText))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *ExampleMsg) String() string {
	return x.MarshalProtoText()
}
func (m *ExampleMsg) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protobuf_go_lite.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExampleMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExampleMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExampleField", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExampleField = append(m.ExampleField[:0], dAtA[iNdEx:postIndex]...)
			if m.ExampleField == nil {
				m.ExampleField = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExampleText", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExampleText = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
